sms_source/sms_source/Areas/admin/Controllers/EventsController.cs
using sms_source.Areas.admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Helper;

namespace sms_source.Areas.admin.Controllers
{
    public class EventsController : Controller
    {
        //
        // GET: /admin/Events/
        DbContext<events> _dbEvents = new DbContext<events>();
        public ActionResult Index()
        {
            _dbEvents.Select();
            _dbEvents.OrderBy("DESC");
            ViewBag.data = _dbEvents.FetchObject();
            
            return View();
        }

        [HttpGet]
        public ActionResult ajaxLoad()
        {
            _dbEvents.Select();
            _dbEvents.OrderBy("DESC");
            ViewBag.data = _dbEvents.FetchObject();
            return View();
        }

        [HttpPost]
        public ActionResult ajaxLoad(events e)
        {
            _dbEvents.Select();
            _dbEvents.Like("event_name", e.event_name, "%{0}%");
            _dbEvents.OrderBy("DESC");
            ViewBag.data = _dbEvents.FetchObject();
            return View();

            //return Content(_dbEvents.test());
        }

        [HttpGet]
        public ActionResult Insert()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Insert(events ev)
        {
            ev.create_date = DateTime.Now;
            ev.update_date = DateTime.Now;

            _dbEvents.Create(ev);
            _dbEvents.Save();

            return RedirectToAction("ajaxLoad");
        }
    }
}

sms_source/sms_source/Areas/admin/Controllers/PartnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sms_source.Areas.admin.Models;
using Helper;

namespace sms_source.Areas.admin.Controllers
{
    public class PartnerController : Controller
    {
        //
        // GET: /admin/Partner/
        DbContext<account> _dbAccount = new DbContext<account>();
        DbContext<partner> _dbPartner = new DbContext<partner>();
        public ActionResult Index()
        {
            _dbPartner.Select();
            _dbPartner.Join<account>("account.id", "partner.account_id");
            _dbPartner.OrderBy("partner.id", "DESC");
            ViewBag.data = _dbPartner.FetchTable();
            return View();
        }

        [HttpGet]
        public ActionResult ajaxLoad()
        {
            _dbPartner.Select();
            _dbPartner.Join<account>("account.id", "partner.account_id");
            _dbPartner.OrderBy("partner.id", "DESC");
            ViewBag.data = _dbPartner.FetchTable();
            
            return View();
        }

        [HttpPost] // danh cho search
        public ActionResult ajaxLoad(FormCollection fl)
        {
            _dbPartner.Select();
            _dbPartner.Join<account>("account.id", "partner.account_id");
            _dbPartner.OrderBy("partner.id", "DESC");
            ViewBag.data = _dbPartner.FetchTable();
            return View();
        }


        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(partner objPartner,FormCollection fl)
        {
            if (fl.Count > 0) {
                account acc = new account { 
                    username = fl.Get("username").ToString(),
                    password = fl.Get("password").ToString(),
                    active = false,
                    role = int.Parse(fl.Get("cbCategoryID"))
                };
                _dbAccount.Create(acc);
                _dbAccount.Save();
                int accid = _dbAccount.id;

                objPartner.account_id = accid;
                objPartner.create_date = DateTime.Now;
                objPartner.update_date = DateTime.Now;
                _dbPartner.Create(objPartner);
                _dbPartner.Save();                

            }

            return RedirectToAction("ajaxLoad", "partner");            
        }

        public ActionResult Update(string id)
        {
            _dbPartner.Select();
            _dbPartner.Where("id", id);
            var obj =_dbPartner.FetchObject()[0];
            ViewBag.partner = obj;

            _dbAccount.Select();
            _dbAccount.Where("id", obj.account_id.ToString());
            ViewBag.account = _dbAccount.FetchObject()[0];

            return View();
        }

    }
}

sms_source/sms_source/Areas/admin/Views/Events/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/admin.cshtml";
    var objEvent = ViewBag.data;
}


<h2>Quản lý Sự Kiện</h2>
<div style="float: left; width: 100%">
    @using (Ajax.BeginForm("ajaxLoad", "events",
                        new AjaxOptions()
                        {
                            UpdateTargetId = "ajaxLoad"
                        },
                        new { @id = "validateForm" }))
    {
        <fieldset>
            <legend>Tiêu chí tìm kiếm</legend>
            <div style="width: 40%; float: left">
                <div class="sub">
                    <div class="editor-label">
                        <label>Tên Sự Kiên:</label>
                    </div>
                    <div class="editor-field">
                        <input type="text" name="event_name" />
                    </div>
                </div>

                <div class="sub">
                    <div class="editor-label">
                        <label>Ngày bắt đầu</label>
                    </div>
                    <div class="editor-field">
                        <input type="datetime-local" name="start_date" style="padding: 4px; width: 250px">
                    </div>

                </div>
            </div>
            <div style="width: 40%; float: left">
                <div class="sub">
                    <div class="editor-label">
                        <label>Trạng thái</label>
                    </div>
                    <div class="editor-field">
                        <select>
                            <option value="0">Chọn</option>
                            <option value="8" selected="selected">Chờ xét duyệt</option>
                            <option value="8">Đang hoạt động</option>
                            <option value="8">Ngừng hoạt đông</option>

                        </select>
                    </div>
                </div>

                <div class="sub">
                    <div class="editor-label">
                        <label>Ngày kết thúc</label>
                    </div>
                    <div class="editor-field">
                        <input type="datetime-local" name="end_date" style="padding: 4px; width: 250px">
                    </div>

                </div>
                <div class="sub">
                    <div style="float: left; width: 100%; padding-left: 320px">
                        <input type="submit" class="button" value="Tìm kiếm" />
                    </div>
                </div>
            </div>

        </fieldset>
    }
</div>

<div style="float: left; width: 100%;">
    <fieldset>
        <legend>Danh sách đầu số</legend>

        <div id="ajaxLoad">
            <table class="tableList" cellspacing="0" rules="all" border="1" id="ctphMain_grvCategories">
                <tr class="header">
                    <td>STT</td>
                    <td>Sự kiện</td>
                    <td>Trạng thái</td>
                    <td>Ngày bắt đầu</td>
                    <td>Ngày kết thúc</td>
                    <td>&nbsp;</td>
                </tr>

                @{
                    int i = 0;
                    foreach (var item in objEvent)
                    {
                        i++;
                    <tr>
                        <td>@(i)</td>
                        <td>@item.event_name</td>
                        <td>Đang hoạt động</td>
                        <td>@item.start_date</td>
                        <td>@item.end_date</td>
                        <td>
                            <a style="width: 60px" title="Sửa" class="table-icon edit"
                                href="javascript:;" data-toggle="modal" data-target="#myModal"></a>
                            <a title="Xóa" class="table-icon delete" href="#"></a>

                        </td>
                    </tr>
                    }
                }

            </table>

        </div>

    </fieldset>
    <div style="float: left; width: 100%;">
        <a style="width: 60px; float: right" href="javascript:;" class="button">Xuất Excel</a>
        @Ajax.ActionLink("Thêm mới", "Insert", "Partner",
            new AjaxOptions()
            {
                UpdateTargetId = "myModal"
            }, new
            {
                style = "width: 60px; float: right",
                data_toggle = "modal",
                data_target = "#myModal",
                @class = "button add"
            })
    </div>
</div>



@*Form Thêm*@
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>


sms_source/sms_source/Areas/admin/Views/Events/Insert.cshtml

<script type="text/javascript">
    $(document).ready(function () {
        $('#validateForm').validate();
    });
</script>

@using (Ajax.BeginForm("Insert", "events",
                        new AjaxOptions() {
                            UpdateTargetId = "ajaxLoad",
                            OnSuccess = "$('#myModal').modal('hide')" 
                        },
                        new { @id = "validateForm" }))
{
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Thông tin</h4>
        </div>
        <div class="modal-body">
            <div>

                <p style="color:gray;font-style:italic;padding-left:40px">
                            Chú ý những phần đánh dấu ( <span style="color:red">*</span> ) sao bắt buộc phải nhập đầy đủ</p>

                <legend>Thêm đầu Sự Kiện</legend>
                <div style="width: 90%;margin:20px auto">
                    <div class="sub">
                        <div class="editor-label">
                            <label for="txtTitle">Tên sự Kiên:</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="event_name" class="required text ui-widget-content ui-corner-all">
                            <label for="event_name" generated="true" class="error" 
                                    style="display: inline;">* Nhập vào tên sự kiện VD: ' Miss FLC ' </label>
                        </div>
                    </div>
                    <div class="sub">
                        <div class="editor-label">
                            <label for="txtTitle">Ngày bắt đầu:</label>
                        </div>
                        <div class="editor-field">
                            <input type="datetime-local" name="start_date" class="required" style="padding:4px;width:250px" />
                            <label for="start_date" generated="true" class="error" 
                                    style="display: inline;">* Thời gian bắt đầu sự kiện </label>
                        </div>
                    </div>

                    <div class="sub">
                        <div class="editor-label">
                            <label for="txtTitle">Ngày kết thúc:</label>
                        </div>
                        <div class="editor-field">
                            <input type="datetime-local" name="end_date" class="required" style="padding:4px;width:250px" />
                            <label for="end_date" generated="true" class="error" 
                                    style="display: inline;">* Thời gian kết thúc sự kiện </label>
                        </div>
                    </div>

                    <div class="sub" style="position:relative">
                        <div class="editor-label" style="margin-top:40px">
                            <label for="txtTitle">Thông tin chung:</label>
                        </div>
                        <div class="editor-field">
                            <textarea cols="40" name="description"></textarea>
                            <p style="position:absolute;right:0;top:0; width:330px;z-index:100;text-align:left">
                                Thông tin về sự kiện, thể lệ, phần thưởng ...</p>
                        </div>
                    </div>
                    
                </div>
                <div style="clear:both"></div>
            </div>

        </div>
        <div class="modal-footer">
            <input type="submit" value="Thêm Mới" class="button add" />            
            <button type="button" class="button" data-dismiss="modal">Hủy</button>
        </div>
    </div>
</div>
}

sms_source/sms_source/Areas/admin/Views/Events/ajaxLoad.cshtml
@{
    var objEvent = ViewBag.data;
}

<table class="tableList" cellspacing="0" rules="all" border="1" id="ctphMain_grvCategories">
    <tr class="header">
        <td>STT</td>
        <td>Sự kiện</td>
        <td>Trạng thái</td>
        <td>Ngày bắt đầu</td>
        <td>Ngày kết thúc</td>
        <td>&nbsp;</td>
    </tr>

    @{
        int i=0;
        foreach (var item in objEvent)
        {
            i++;
        <tr>
            <td>@(i)</td>
            <td>@item.event_name</td>
            <td>Đang hoạt động</td>
            <td>@item.start_date</td>
            <td>@item.end_date</td>
            <td>
                <a style="width: 60px" title="Sửa" class="table-icon edit"
                    href="javascript:;" data-toggle="modal" data-target="#myModal"></a>
                <a title="Xóa" class="table-icon delete" href="#"></a>

            </td>
        </tr>
        }
    }

</table>