sms_source/Areas/admin/Models/service_numbers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sms_source.Areas.admin.Models
{
    public class service_numbers
    {
        public int id { get; set; }
        public int service { get; set; }       
        public DateTime create_date { get; set; }
        public DateTime update_date { get; set; }
        public bool active { get; set; }
        public float price { get; set; }
    }
}

sms_source/Areas/admin/Controllers/ServiceNumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Helper;
using sms_source.Areas.admin.Models;

namespace sms_source.Areas.admin.Controllers
{
    public class ServiceNumberController : Controller
    {
        //
        // GET: /admin/ServiceNumber/
        readonly DbContext<service_numbers> _dbContext = new DbContext<service_numbers>();
        readonly DbContext<service_rates> _dbContextServiceRate = new DbContext<service_rates>();
        readonly DbContext<telcos> _dbContextTelcos = new DbContext<telcos>();

        public ActionResult Index(int? delID)
        {
            if (delID != null)
            {
                //Delete Bảng giữa
                _dbContextServiceRate.Where("service_id",delID.Value.ToString());
                _dbContextServiceRate.Delete();
                _dbContextServiceRate.Save();

                //Delete Bảng chính
                _dbContext.Where("id", delID.Value.ToString());
                _dbContext.Delete();
                _dbContext.Save();
            }
            _dbContext.Select();
            var lstServiceNumber = _dbContext.FetchObject();            
            return View(lstServiceNumber);
        }

        public ActionResult Insert()
        {
            _dbContextTelcos.Select(new[] { "id", "telcos_name" });
            ViewBag.lstTelcos = _dbContextTelcos.FetchObject();
            return View();
        }

        [HttpPost]
        public ActionResult Insert(int countTelco, service_numbers model)
        {
            if (ModelState.IsValid)
            {
                //Thực hiện Insert Bảng Service_Number
                var modelInsert = new service_numbers
                {
                    service = model.service,
                    create_date = DateTime.Parse(DateTime.Now.ToLongDateString()),
                    update_date = DateTime.Parse(DateTime.Now.ToLongDateString()), // model.update_date
                    active = bool.Parse(Request["cbStatus"])
                };
                _dbContext.Create(modelInsert);
                _dbContext.Save();
                var topID = _dbContext.id;

                //Thực hiện Insert Bảng Service_rate
                for (var i = 0; i < countTelco; i++)
                {
                    var objServiceTelco = new service_rates
                        {
                            service_id = topID,
                            telcos_id = int.Parse(Request["hdTelcoID" + i]),
                            price = string.IsNullOrEmpty((Request["txtPrice" + i])) ? 0 : float.Parse(Request["txtPrice" + i])
                        };
                    _dbContextServiceRate.Create(objServiceTelco);
                    _dbContextServiceRate.Save();
                }

                return Content("OK");
            }

            return View(model);
        }

        public ActionResult Update(int? id)
        {
            if (id != null)
            {                
                _dbContextTelcos.Select(new[] { "id", "telcos_name" });
                ViewBag.lstTelcos = _dbContextTelcos.FetchObject();

                _dbContext.Select();
                _dbContext.Where("id", id.Value.ToString());
                var listServiceNumber = _dbContext.FetchObject();
                return View(listServiceNumber[0]);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Update(int countTelco, service_numbers model)
        {
            
            if (ModelState.IsValid)
            {
                //Thực hiện Update Bảng Service_Number                
                _dbContext.Where("id", model.id.ToString());
                _dbContext.Update(new service_numbers
                {
                    service = model.service,
                    create_date = model.create_date,
                    update_date = DateTime.Parse(DateTime.Now.ToLongDateString()), // model.update_date
                    active = bool.Parse(Request["cbStatus"])
                });                
                _dbContext.Save();

                //Thực hiện Update Bảng Service_rate
                for (var i = 0; i < countTelco; i++)
                {
                    
                    var objServiceTelco = new service_rates
                    {
                        service_id = model.id,
                        telcos_id = int.Parse(Request["hdTelcoID" + i]),
                        price = float.Parse(Request["txtPrice" + i])
                    };
                    _dbContextServiceRate.Where("service_id", objServiceTelco.service_id.ToString());
                    _dbContextServiceRate.Where("telcos_id", objServiceTelco.telcos_id.ToString());
                    _dbContextServiceRate.Update(objServiceTelco);
                    _dbContextServiceRate.Save();
                }

                return Content("OK");
            }

            return View(model);
        }

    }
}

sms_source/Areas/admin/Views/ServiceNumber/Index.cshtml
@using Helper
@using sms_source.Areas.admin.Models
@model List<service_numbers>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/admin.cshtml";
}


<h2>Quản lý đầu số dịch vụ</h2>
<div style="float: left; width: 100%">
    <label>Chọn đầu số:</label>
    <select>
        <option value="0">7x47</option>
    </select>
</div>

<div style="float: left; width: 100%;">
    <fieldset>
        <legend>Danh sách đầu số</legend>
        <table class="tableList">
            @{
                var dbTelco = new DbContext<telcos>();
                dbTelco.Select();
                var lstTelco = dbTelco.FetchObject();
                
            }
            <tr class="header">
                <th scope="col" style="width: 30px;" rowspan="2">STT</th>
                <th scope="col" style="width: 10%;" rowspan="2">Đầu số</th>
                <th scope="col" style="width: 50%;" colspan="@(lstTelco.Count)">Giá nhận từ nhà mạng (vnđ)</th>
                <th scope="col"  rowspan="2" >Giá cước chung (vnđ)</th>
                <th scope="col" style="width: 15%;" rowspan="2">Trạng thái</th>
                <th scope="col" style="width: 50px;" rowspan="2">&nbsp;</th>
            </tr>
            <tr class="header">
                @for (int i = 0; i < lstTelco.Count; i++)
                {
                    <th>@lstTelco[i].telcos_name</th>
                }

            </tr>
            @{                
                for (int i = 0; i < Model.Count; i++)
                {
                <tr>
                    <td align="center">
                        <span id="ctphMain_grvCategories_lblSTT_0">@(i + 1)</span>
                    </td>
                    <td>
                        <span id="ctphMain_grvCategories_lblCategoryName_0">@Model[i].service</span>
                    </td>

                    @for (int j = 0; j < lstTelco.Count; j++)
                    {
                        var price = dbTelco.getColumnValue("service_rates", "price", new Dictionary<string, string>
                                {
                                    {"service_id", Model[i].id.ToString()},
                                    {"telcos_id", lstTelco[j].id.ToString()},

                                });
                        if (price == "")
                        {
                        <td>0</td>
                        }
                        else
                        {
                        <td>@price</td>
                        }

                    }
                    <td>
                        <span>@Model[i].price</span>
                    </td>
                    @{
                    if (Model[i].active)
                    {
                        <td>
                            <span>Đang hoạt động</span>
                        </td>
                    }
                    else
                    {
                        <td>
                            <span>Ngừng hoạt động</span>
                        </td>
                    }
                    }

                    <td>
                        @Ajax.ActionLink(" ", "Update", "ServiceNumber",
                                         new { id = @Model[i].id },
                                         new AjaxOptions() { UpdateTargetId = "myModal" },
                                         new
                                         {
                                             @class = "table-icon edit",
                                             @title = "Sửa",
                                             data_toggle = "modal",
                                             data_target = "#myModal",
                                             style = "width: 60px;"
                                         })

                        @Ajax.ActionLink(" ", "Index", "ServiceNumber",
                                         new { delID = @Model[i].id },
                                         new AjaxOptions() { Confirm = "Delete?"},
                                         new { @class = "table-icon delete", @title = "Xóa", style = "width: 60px;" })
                    </td>
                </tr>
                }
            }



        </table>
    </fieldset>
    <div style="float: left; width: 100%;">
        <a style="width: 60px; float: right" href="javascript:;" class="button">Xuất Excel</a>

        @Ajax.ActionLink("Thêm mới", "Insert", "ServiceNumber", new AjaxOptions() { UpdateTargetId = "myModal" },
        new { @class = "button add", data_toggle = "modal", data_target = "#myModal", style = "width: 60px; float: right" })
    </div>
</div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

sms_source/Areas/admin/Views/ServiceNumber/Insert.cshtml
@model sms_source.Areas.admin.Models.service_numbers
@{
    var lstTelco = (List<sms_source.Areas.admin.Models.telcos>)ViewBag.lstTelcos;
}
@using (Ajax.BeginForm("Insert", "ServiceNumber",new{countTelco = lstTelco.Count} ,new AjaxOptions() { UpdateTargetId = "result" })){
<div id="result"></div>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Thông tin</h4>
        </div>
        <div class="modal-body">
            <div>
                <fieldset>
                    <legend>Thêm đầu số tổng đài</legend>
                    <div style="float: left; width: 45%;">
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Đầu số:</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.service, new
                           {
                               @required = "required",
                               @class = "text ui-widget-content ui-corner-all",
                               @style = "width: 200px"
                           })
                            </div>

                        </div>
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Giá thu từ Khách hàng:</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.price, new
                                    {
                                        @required = "required",
                                        @class = "text ui-widget-content ui-corner-all",
                                        @style = "width: 200px"
                                    })
                            </div>

                        </div>
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Trạng thái:</label>
                            </div>
                            <div class="editor-field">
                                <select name="cbStatus">
                                    <option value="true">Đang hoạt động</option>
                                    <option value="false">Ngừng hoạt động</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div style="float: left; width: 55%;">
                        <fieldset>
                            <legend>Giá nhận từ nhà mạng (vnđ)</legend>
                            @for (int i = 0; i < lstTelco.Count; i++ )
                            {                                
                                <input type="hidden" name="hdTelcoID@(i)" value="@lstTelco[i].id" />
                                <div class="sub">
                                    <div class="editor-label">
                                        <label for="txtTitle">@lstTelco[i].telcos_name:</label>
                                    </div>
                                    <div class="editor-field">                                        
                                        <input type="number" name="txtPrice@(i)" class="text ui-widget-content ui-corner-all">
                                    </div>
                                </div>
                            }                         
                        </fieldset>
                    </div>
                </fieldset>
            </div>

        </div>
        <div class="modal-footer">
            <button type="submit" class="button add">Thêm mới</button>
            <button type="button" class="button" data-dismiss="modal">Hủy</button>
        </div>
    </div>
</div>
}

sms_source/Areas/admin/Views/ServiceNumber/Update.cshtml
@using sms_source.Areas.admin.Models
@model service_numbers
@{
    var lstTelco = (List<telcos>)ViewBag.lstTelcos;
}
@using (Ajax.BeginForm("Update", "ServiceNumber", new { countTelco = lstTelco.Count }, new AjaxOptions() { UpdateTargetId = "result" })){
<div id="result"></div>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Thông tin</h4>
        </div>
        <div class="modal-body">
            <div>
                <fieldset>
                    <legend>Sửa thông tin đầu số tổng đài</legend>
                    <div style="float: left; width: 45%;">
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Đầu số:</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.service, new
                           {
                               @required = "required",
                               @class = "text ui-widget-content ui-corner-all",
                               @style = "width: 200px"
                           })
                            </div>
                        </div>
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Giá thu từ khách hàng:</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(model => model.price, new
                           {
                               @required = "required",
                               @class = "text ui-widget-content ui-corner-all",
                               @style = "width: 200px"
                           })
                            </div>
                        </div>
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Trạng thái:</label>
                            </div>
                            <div class="editor-field">
                                <select name="cbStatus">
                                    @{
                                        if (Model.active)
                                        {
                                        <option value="true">Đang hoạt động</option>
                                        <option value="false">Ngừng hoạt động</option>
                                        }
                                        else
                                        {                                            
                                        <option value="false">Ngừng hoạt động</option>
                                        <option value="true">Đang hoạt động</option>
                                        }

                                    }
                                </select>
                            </div>
                        </div>
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Ngày khởi tạo:</label>
                            </div>
                            <div class="editor-field">
                                @Html.DisplayTextFor(model => model.create_date)
                                @Html.HiddenFor(model => model.create_date)
                            </div>
                        </div>
                        <div class="sub">
                            <div class="editor-label">
                                <label for="txtTitle">Lần cập nhật cuối:</label>
                            </div>
                            <div class="editor-field">
                                @*<input type="date" readonly="readonly" name="txtTitle" id="txtUpdateDate" class="text ui-widget-content ui-corner-all">*@
                                @Html.DisplayTextFor(model => model.update_date)
                                @Html.HiddenFor(model => model.update_date)
                            </div>
                        </div>

                    </div>
                    <div style="float: left; width: 55%;">
                        <fieldset>
                            <legend>Giá nhận từ nhà mạng (vnđ)</legend>
                            @for (int i = 0; i < lstTelco.Count; i++)
                            {
                                var dbServiceRate = new Helper.DbContext<service_rates>();
                                dbServiceRate.Select();
                                dbServiceRate.Where("telcos_id", lstTelco[i].id.ToString());
                                dbServiceRate.Where("service_id", Model.id.ToString());
                                var objRate = dbServiceRate.FetchObject()[0];
                                              
                                <input type="hidden" name="hdTelcoID@(i)" value="@lstTelco[i].id" />
                                <div class="sub">
                                    <div class="editor-label">
                                        <label for="txtTitle">@lstTelco[i].telcos_name:</label>
                                    </div>
                                    <div class="editor-field">
                                        <input type="number" name="txtPrice@(i)" value="@objRate.price" class="text ui-widget-content ui-corner-all">
                                    </div>
                                </div>
                            }
                        </fieldset>
                    </div>
                </fieldset>
            </div>

        </div>
        <div class="modal-footer">
            <button type="submit" class="button save">Cập nhật</button>
            <button type="button" class="button" data-dismiss="modal">Hủy</button>
        </div>
    </div>
</div>
}